### ISSUE TITLE
Improve ReadMe or add some documents

### ISSUE THREAD

**Issue by r12f** [hufuman/nui#1]

**Comment by hufuman** [comment]
code is document.
now it's far from usable.

**Comment by r12f** [comment]
Some simple guidance / examples in readme should be enough, when the time is good for you. It could be very helpful for people to find out if this project is what they want at the first glance, so they don't have to compile / read the code / debugging it for a relatively long time.

**Comment by hufuman** [comment]
got it.
hope DaShen help me.

**Comment by r12f** [comment]
O.O

**Comment by hufuman** [comment]
https://github.com/google/gxui

**Comment by r12f** [comment]
Aha, +1. I forgot to star this project.

**Comment by r12f** [comment]
Will you work on it?

**Comment by hufuman** [comment]
contribute to gxui, and you could go to google.

**Comment by r12f** [comment]
I think I will get fired first. Hahahaha.

**Comment by hufuman** [comment]
never use go, should be easy. and i want to develop one simple game DropN, after Drop7.
